name: CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  Build_And_Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Formatter
        run: rustup component add rustfmt

      - name: Install Clippy
        run: rustup component add clippy

      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Build
        run: cargo build

      - name: Check Formatting
        run: cargo fmt --all -- --check

      - name: Run Cargo Clippy
        run: cargo clippy

      - name: Run Tests
        run: cargo test

      - name: Check Coverage
        run: cargo tarpaulin